# Generated by Django 3.0.3 on 2021-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('comment', models.TextField()),
                ('contract_name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('didox', models.IntegerField()),
            ],
        ),
    ]
