# Generated by Django 3.0.3 on 2021-02-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
