# Generated by Django 3.1.4 on 2021-02-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0002_contracts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='client_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='didox',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='path',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='type',
            field=models.IntegerField(default='1'),
        ),
    ]
