# Generated by Django 3.1.4 on 2021-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0003_auto_20210221_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='captcha',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
