# Generated by Django 3.1.4 on 2021-03-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0005_client_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
