# Generated by Django 3.1.4 on 2021-03-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0006_auto_20210306_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
