# Generated by Django 3.1.4 on 2021-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0007_auto_20210306_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
