# Generated by Django 3.1.4 on 2021-03-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0011_auto_20210308_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
