# Generated by Django 3.1.4 on 2021-03-09 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractApp', '0012_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='role_id',
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
