# Generated by Django 3.1.4 on 2021-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0013_auto_20210309_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
