# Generated by Django 3.1.4 on 2021-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0014_role_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
