# Generated by Django 3.1.4 on 2021-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0015_role_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='path_to_file',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
