# Generated by Django 3.1.4 on 2021-03-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractApp', '0016_role_path_to_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='path_to_file',
        ),
    ]
